#Makefile

CC = wcc386
CCOPTS =  /w4 /oneatx /oh /ei /zp8 /6 /fp6

all :           fs.exe

fs.exe :      fs.obj  write.obj
        wlink @rps.wlk 

fs.obj :       fs.c
        $(CC) fs.c $(CCOPTS)

write.obj :     write.c
	$(CC) write.c $(CCOPTS)

